# Generated by Django 4.2.6 on 2023-10-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('code', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name="Tickets' code")),
                ('name', models.CharField(max_length=50, verbose_name='Description')),
                ('maxPurchaseCount', models.PositiveIntegerField(verbose_name='Maximum purchase count number')),
                ('purchaseCount', models.PositiveIntegerField(verbose_name='Purchase count number')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
