# Generated by Django 4.2.6 on 2023-10-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_tickets_soldout_alter_tickets_code_purchasedtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtickets',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity purchased'),
            preserve_default=False,
        ),
    ]
