# Generated by Django 4.2.6 on 2023-10-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_purchasedtickets_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtickets',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tickets', verbose_name='Ticket'),
        ),
    ]
