# Generated by Django 4.2.6 on 2023-10-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_maxpurchasecount_tickets_max_purchase_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedtickets',
            old_name='guestName',
            new_name='guest_name',
        ),
    ]
